apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: queue
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: queue
        name: queue
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-queue:release2
        name: queue
        ports:
        -  containerPort: 8161